Update/Refactor sun_misc_Unsafe peer class to jdk_internal_misc_Unsafe
Rename JPF_sun_misc_Unsafe.java to JPF_jdk_internal_misc_Unsafe

This implements the missing methods in Unsafe model class to prevent:
[junit] java.lang.NoSuchMethodError: jdk.internal.misc.Unsafe.objectFieldOffset(Ljava/lang/Class;Ljava/lang/String;)J

And implement respective NativePeer methods in JPF_jdk_internal_misc_Unsafe, to prevent:
[junit] java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.misc.Unsafe.objectFieldOffset