Remove unused import com.sun.org.apache.bcel.internal.generic.InstructionConstants (#19)
Fixes the compile error:
  error: package com.sun.org.apache.bcel.internal.generic does not exist

Fixes: #19