Implement missing, and/or unlinked native methods in Unsafe  (#105)
* Update/Refactor sun_misc_Unsafe peer class to jdk_internal_misc_Unsafe

Rename JPF_sun_misc_Unsafe.java to JPF_jdk_internal_misc_Unsafe

This implements the missing methods in Unsafe model class to prevent:
[junit] java.lang.NoSuchMethodError: jdk.internal.misc.Unsafe.objectFieldOffset(Ljava/lang/Class;Ljava/lang/String;)J

And implement respective NativePeer methods in JPF_jdk_internal_misc_Unsafe, to prevent:
[junit] java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.misc.Unsafe.objectFieldOffset

* Add gov.nasa.jpf.test.java.misc.UnsafeTest

This exports java.base/jdk.internal.misc to the UNNAMED module (in ant
target --compile-tests), so to be able to reference
gov.nasa.jpf.test.java.misc.UnsafeTest within UnsafeTest

So to prevent:
    [javac] src/tests/gov/nasa/jpf/test/java/misc/UnsafeTest.java:4: error: package jdk.internal.misc is not visible
    [javac] import jdk.internal.misc.Unsafe;
    [javac]                    ^
    [javac]   (package jdk.internal.misc is declared in module java.base, which does not export it to the unnamed module)