Add gov.nasa.jpf.test.java.misc.UnsafeTest
This exports java.base/jdk.internal.misc to the UNNAMED module (in ant
target --compile-tests), so to be able to reference
gov.nasa.jpf.test.java.misc.UnsafeTest within UnsafeTest

So to prevent:
    [javac] src/tests/gov/nasa/jpf/test/java/misc/UnsafeTest.java:4: error: package jdk.internal.misc is not visible
    [javac] import jdk.internal.misc.Unsafe;
    [javac]                    ^
    [javac]   (package jdk.internal.misc is declared in module java.base, which does not export it to the unnamed module)