Refactor a reference to sun.misc.Unsafe
This refactors sun.misc.Unsafe to jdk.internal.misc.Unsafe in
JPF_java_util_Random.java

So to fix the compiler warning:

    [javac] /home/travis/build/javapathfinder/jpf-core/src/peers/gov/nasa/jpf/vm/JPF_java_util_Random.java:99:
     warning: Unsafe is internal proprietary API and may be removed in a future release

However package jdk.internal.misc is declared in module java.base, which does
not export it to the unnamed module (src/peers)

So following compiler argument is neceesary to be added into javac ant
target of src/peers

    <compilerarg value="--add-exports"/>
    <compilerarg value="java.base/jdk.internal.misc=ALL-UNNAMED"/>

to prevent the error:

    [javac] /home/gayan/git/javapathfinder/jpf-core/src/peers/gov/nasa/jpf/vm/JPF_java_util_Random.java:32:
               error: package jdk.internal.misc is not visible
    [javac] import jdk.internal.misc.Unsafe;
    [javac]                    ^
    [javac]   (package jdk.internal.misc is declared in module java.base, which does not export it to the unnamed module)

Fixes: #68